ckeditor5.plugin.printables_embed_plugin:
  type: mapping
  label: 'Printables Embed'
  mapping:
    toolbar_items:
      type: mapping
      label: 'Toolbar items'
      mapping:
        printablesEmbed:
          type: ckeditor5.toolbar_item
          label: 'Printables Embed Button'